### ISSUE TITLE
renderer crashes when hydrogen is burned

### ISSUE THREAD

**Issue by otter502** [Elkwizard/SandSim#1]
when hydrogen is burnt it makes the renderer stop rendering the frame

I looked over the code and found that the issue was some added code at the end of the onBurned listener
```js
[TYPES.HYDROGEN]: new Element(0, [new Color("#55cdfc"), new Color("#47add6")], 0, .5, (x, y) => {
		gasUpdate(x, y);
	}, (x, y) => {
		if (Random.bool(.03)) {
			Element.setCell(x, y, TYPES.WATER);
			return true;
		}SH
	}),
```
line 2418
the SH at the end seems to throw an error

**Comment by Elkwizard** [comment]
Removed SH, Fixed
